### ISSUE TITLE
ModuleNotFoundError: No module named 'earl_benchmark’

### ISSUE THREAD

**Issue by dzy666fly** [architsharma97/earl_benchmark#1]
Hello! Thanks for sharing the benchmark. After using conda to create environment earl and activate it , error ouccurs. 
`import earl_benchmark
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'earl_benchmark’`
Maybe something is missed in env.yml? How can I solve this problem?

**Comment by architsharma97** [comment]
Hi,
Thanks for raising the issue. We updated the repository and instructions to make the repository a pip package. Hopefully, that should make it easier to work and import earl_benchmark. Please let us know if the updated instructions do not resolve the issue.

**Comment by dzy666fly** [comment]
Thanks you very much. This issue is resovled. Well, after creating environment with code `conda create -n earl python=3.7` and
`pip install -e .`, it shows
 'File "xxx/anaconda3/envs/earl/lib/python3.7/site-packages/gym/envs/mujoco/mujoco_rendering.py", line 8, in <module>
import mujoco
ModuleNotFoundError: No module named 'mujoco''.
So I run 'pip install mujoco'. In fact, mujoco has been added to related folder and .bashrc. It is a bit confusing.

**Comment by architsharma97** [comment]
Hi,
You shouldn't require `pip install mujoco`. We updated the requirement in the `env.yml`/`setup.py` to use the compatible version of the gym (which should avoid using this issue). Please try recreating the environment, and let us know if the issue persists. Thanks!
